language: php

env:
  - APP_ENV=travis

php:
  - 7.1
  - hhvm
  - nightly

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit
