language: php

env:
  - APP_ENV=travis

php:
  - 5.6
  - hhvm
  - nightly

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - phpunit
